1. Our corpus will have 12 documents
2. The average document length is 72786.
3. The min length is: 4023 (The Monkey's Paw) and the max length is: 294507 (Udolpho).
4. The OHCO structure is ['book_id', 'chap_num', 'para_num', 'sent_num', 'token_num']

In [27]:
import pandas as pd

In [28]:
OHCO = ['doc_id', 'chap_num', 'para_num', 'sent_num', 'token_num']

# High Gothic

Novels: 
1. Castle of Otranto by Horace Walpole
2. The Old English Baron by Clara Reeve
3. The Mysteries of Udolpho by Ann Radcliffe

Code for converting all into OHCO structure can be found: https://www.kaggle.com/code/mohiniguptarde/notebooka9f19dc16f/edit or in the raw-text-to-corpus.ipynb file

In [29]:
high_gothic_corpus = pd.read_csv("Data\CORPUS\high-goth-and-melmoth\hg-corpus.csv").set_index(OHCO)

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_39048\1617144110.py:1: SyntaxWarning: invalid escape sequence '\C'
  high_gothic_corpus = pd.read_csv("Data\CORPUS\high-goth-and-melmoth\hg-corpus.csv").set_index(OHCO)

In [30]:
high_gothic_corpus = high_gothic_corpus.rename_axis(index={'doc_id': 'book_id'})

In [31]:
high_gothic_corpus

                                                         pos_tuple   pos  \
book_id chap_num para_num sent_num token_num
3268    1        0        0        0                ('home', 'NN')    NN
                                   1                 ('is', 'VBZ')   VBZ
                                   2                 ('the', 'DT')    DT
                                   3              ('resort', 'NN')    NN
                                   4                  ('Of', 'IN')    IN
...                                                            ...   ...
696     5        121      5        41             ('taken', 'VBN')   VBN
                                   42         ('possession', 'NN')    NN
                                   43                 ('of', 'IN')    IN
                                   44              ('his', 'PRP$')  PRP$
                                   45               ('soul', 'NN')    NN

                                               token_str    term_str pos_group
book_id chap_num para_num sent_num token_num
3268    1        0        0        0                home        home        NN
                                   1                  is          is        VB
                                   2                 the         the        DT
                                   3              resort      resort        NN
                                   4                  Of          of        IN
...                                                  ...         ...       ...
696     5        121      5        41              taken       taken        VB
                                   42         possession  possession        NN
                                   43                 of          of        IN
                                   44                his         his        PR
                                   45               soul        soul        NN

[184412 rows x 5 columns]

In [32]:

otranto = pd.read_csv('Data\TOKENS\otranto-TOKENS.csv')
baron = pd.read_csv('Data/TOKENS/baron-TOKENS.csv')

udolpho = pd.read_csv('Data/TOKENS/udolpho-TOKENS.csv')

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\school\AppData\Local\Temp\ipykernel_39048\590428128.py:1: SyntaxWarning: invalid escape sequence '\T'
  otranto = pd.read_csv('Data\TOKENS\otranto-TOKENS.csv')

In [33]:
print("Udolpho len: ", len(udolpho))
print("BAron len: ", len(baron))
print("Otranto len: ", len(otranto))

Udolpho len:  80568
BAron len:  63628
Otranto len:  40216

# Classic/Romantic Gothic

Novels:
1. Frankenstein by Mary Shelley
2. Melmoth the Wanderer, Vol. 1 by Charles Robert Maturin
3. The Vampyre by John Polidori

Code links:

Melmoth: https://www.kaggle.com/code/mohiniguptarde/notebooka9f19dc16f/edit

In [34]:
OHCO = ['book_id', 'chap_num', 'para_num', 'sent_num', 'token_num']

In [35]:
melmoth = pd.read_csv('Data\TOKENS\melmoth-TOKENS.csv').set_index([ 'chap_num', 'para_num', 'sent_num', 'token_num'])
melmoth = pd.concat([melmoth], keys=[53685], names=['book_id'])
frankenstein = pd.read_csv("Data/TOKENS/frankenstein_OHCO").set_index(OHCO)
vampyre = pd.read_csv('Data\TOKENS\pg6087-TOKENS.csv').set_index([ 'chap_num', 'para_num', 'sent_num', 'token_num'])
vampyre = pd.concat([vampyre], keys=[6087], names=['book_id'])
print("Melmoth len: ", len(melmoth))
print("Frankenstein len: ", len(frankenstein))
print("Vampyre len: ", len(vampyre))

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:4: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:4: SyntaxWarning: invalid escape sequence '\T'
C:\Users\school\AppData\Local\Temp\ipykernel_39048\2242499493.py:1: SyntaxWarning: invalid escape sequence '\T'
  melmoth = pd.read_csv('Data\TOKENS\melmoth-TOKENS.csv').set_index([ 'chap_num', 'para_num', 'sent_num', 'token_num'])
C:\Users\school\AppData\Local\Temp\ipykernel_39048\2242499493.py:4: SyntaxWarning: invalid escape sequence '\T'
  vampyre = pd.read_csv('Data\TOKENS\pg6087-TOKENS.csv').set_index([ 'chap_num', 'para_num', 'sent_num', 'token_num'])

Melmoth len:  66304
Frankenstein len:  67204
Vampyre len:  11076

In [36]:
classic_corp_list = [melmoth, frankenstein, vampyre]
ids = [53685, 84, 6087]
HG_CORPUS = pd.concat(classic_corp_list)
HG_CORPUS.to_csv("Data\CORPUS\classic-gothic\classic-corpus.csv")

<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_39048\1470012567.py:4: SyntaxWarning: invalid escape sequence '\C'
  HG_CORPUS.to_csv("Data\CORPUS\classic-gothic\classic-corpus.csv")

# Victorian Gothic

In [37]:
OHCO = ['book_id', 'chap_num', 'para_num', 'sent_num', 'token_num']

jekyll_and_hyde = pd.read_csv('Data\TOKENS\pg43-TOKENS.csv').set_index(OHCO)
dracula = pd.read_csv('Data\TOKENS\pg345-TOKENS.csv').set_index(OHCO)
yellow_wallpaper = pd.read_csv('Data\TOKENS\pg1952-TOKENS.csv').set_index(OHCO)

<>:3: SyntaxWarning: invalid escape sequence '\T'
<>:4: SyntaxWarning: invalid escape sequence '\T'
<>:5: SyntaxWarning: invalid escape sequence '\T'
<>:3: SyntaxWarning: invalid escape sequence '\T'
<>:4: SyntaxWarning: invalid escape sequence '\T'
<>:5: SyntaxWarning: invalid escape sequence '\T'
C:\Users\school\AppData\Local\Temp\ipykernel_39048\3183730349.py:3: SyntaxWarning: invalid escape sequence '\T'
  jekyll_and_hyde = pd.read_csv('Data\TOKENS\pg43-TOKENS.csv').set_index(OHCO)
C:\Users\school\AppData\Local\Temp\ipykernel_39048\3183730349.py:4: SyntaxWarning: invalid escape sequence '\T'
  dracula = pd.read_csv('Data\TOKENS\pg345-TOKENS.csv').set_index(OHCO)
C:\Users\school\AppData\Local\Temp\ipykernel_39048\3183730349.py:5: SyntaxWarning: invalid escape sequence '\T'
  yellow_wallpaper = pd.read_csv('Data\TOKENS\pg1952-TOKENS.csv').set_index(OHCO)

In [38]:
print("Jekyll and Hyde len: ", len(jekyll_and_hyde))
print("Dracula len: ", len(dracula))
print("Yellow Wallpaper len: ", len(yellow_wallpaper))

Jekyll and Hyde len:  25993
Dracula len:  164373
Yellow Wallpaper len:  6200

# Modern Gothic

In [39]:
modern_gothic_corpus = pd.read_csv("Data\CORPUS\modern-gothic-corpus\ModernGothic-CORPUS").set_index(OHCO)

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_39048\4187357471.py:1: SyntaxWarning: invalid escape sequence '\C'
  modern_gothic_corpus = pd.read_csv("Data\CORPUS\modern-gothic-corpus\ModernGothic-CORPUS").set_index(OHCO)

In [40]:
modern_gothic_corpus

                                              token_str  pos pos_group  \
book_id  chap_num para_num sent_num token_num
175      1        1        0        0                It  PRP        PR
                                    1               was  VBD        VB
                                    2               the   DT        DT
                                    3           evening   NN        NN
                                    4                on   IN        IN
...                                                 ...  ...       ...
20180856 9        119      4        34         whatever  WDT        WD
                                    35           walked  VBD        VB
                                    36            there   RB        RB
                                    38           walked  VBD        VB
                                    39            alone   RB        RB

                                               term_str
book_id  chap_num para_num sent_num token_num
175      1        1        0        0                it
                                    1               was
                                    2               the
                                    3           evening
                                    4                on
...                                                 ...
20180856 9        119      4        34         whatever
                                    35           walked
                                    36            there
                                    38           walked
                                    39            alone

[153163 rows x 4 columns]

In [41]:
print("Phantom of the Opera len: ", len(modern_gothic_corpus.query('book_id == 175')))
print("Monkey's Paw len: ", len(modern_gothic_corpus.query('book_id == 12122')))
print("Haunting of Hill House len: ", len(modern_gothic_corpus.query('book_id == 20180856')))

Phantom of the Opera len:  83686
Monkey's Paw len:  4023
Haunting of Hill House len:  65454

In [42]:
avg_len = (294507 + 57043 + 35635 + 58247 + 67204 + 11076 + 25993 + 164373 + 6200 + 83686 + 65454 + 4023)/12
avg_len

72786.75

# Concat Full CORPUS

In [44]:
hg = pd.read_csv('Data\CORPUS\high-goth-and-melmoth\hg-corpus.csv').set_index(OHCO)
cg = pd.read_csv('Data\CORPUS\classic-gothic\classic-corpus.csv').set_index(OHCO)
mg = pd.read_csv('Data\CORPUS\modern-gothic-corpus\ModernGothic-CORPUS').set_index(OHCO)
vg = pd.read_csv('Data/CORPUS/victorian-and-vampyre/victorian-corpus.csv').set_index(OHCO)

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_39048\1022163194.py:1: SyntaxWarning: invalid escape sequence '\C'
  hg = pd.read_csv('Data\CORPUS\high-goth-and-melmoth\hg-corpus.csv').set_index(OHCO)
C:\Users\school\AppData\Local\Temp\ipykernel_39048\1022163194.py:2: SyntaxWarning: invalid escape sequence '\C'
  cg = pd.read_csv('Data\CORPUS\classic-gothic\classic-corpus.csv').set_index(OHCO)
C:\Users\school\AppData\Local\Temp\ipykernel_39048\1022163194.py:3: SyntaxWarning: invalid escape sequence '\C'
  mg = pd.read_csv('Data\CORPUS\modern-gothic-corpus\ModernGothic-CORPUS').set_index(OHCO)
C:\Users\school\AppData\Local\Temp\ipykernel_39048\1022163194.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  cg = pd.read_csv('Data\CORPUS\classic-gothic\classic-corpus.csv').set_index(OHCO)

In [45]:
classic_corp_list = [hg, cg, mg, vg]

FULL_CORPUS = pd.concat(classic_corp_list)
FULL_CORPUS.to_csv("Data\CORPUS\FULL_CORPUS.csv")

<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_39048\672799057.py:4: SyntaxWarning: invalid escape sequence '\C'
  FULL_CORPUS.to_csv("Data\CORPUS\FULL_CORPUS.csv")

In [46]:
len(FULL_CORPUS)

678725