In [1]:
!pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly) (26.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\school\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

In [3]:
LIB = pd.read_csv('Data\LIB.csv').set_index('book_id').dropna()
TFIDF_L2 = pd.read_csv('Data\TFIDF_L2.csv').set_index('book_id')

<>:1: SyntaxWarning: invalid escape sequence '\L'
<>:2: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\L'
<>:2: SyntaxWarning: invalid escape sequence '\T'
C:\Users\school\AppData\Local\Temp\ipykernel_2936\3541674200.py:1: SyntaxWarning: invalid escape sequence '\L'
  LIB = pd.read_csv('Data\LIB.csv').set_index('book_id').dropna()
C:\Users\school\AppData\Local\Temp\ipykernel_2936\3541674200.py:2: SyntaxWarning: invalid escape sequence '\T'
  TFIDF_L2 = pd.read_csv('Data\TFIDF_L2.csv').set_index('book_id')

## PCA DCM

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD

In [5]:
!pip install plotly_express

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly_express in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (0.4.1)
Requirement already satisfied: pandas>=0.20.0 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly_express) (2.3.1)
Requirement already satisfied: plotly>=4.1.0 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly_express) (6.7.0)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly_express) (0.14.5)
Requirement already satisfied: scipy>=0.18 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly_express) (1.16.1)
Requirement already satisfied: patsy>=0.5 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly_express) (1.0.1)
Requirement already satisfied: numpy>=1.11 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly_express) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=0.20.0->plotly_express) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=0.20.0->plotly_express) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=0.20.0->plotly_express) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly>=4.1.0->plotly_express) (2.19.0)
Requirement already satisfied: packaging in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly>=4.1.0->plotly_express) (26.0)
Requirement already satisfied: six>=1.5 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas>=0.20.0->plotly_express) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\school\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [6]:
import plotly.express as px
import plotly.io as pio
pio.renderers.default = 'notebook_connected'

In [7]:
pca_engine = PCA(n_components=5)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF_L2), index=TFIDF_L2.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

            PC0       PC1       PC2       PC3       PC4
book_id
43       -8.848 -0.000228 -0.000409 -0.000012  0.000733
43       -7.848 -0.000279 -0.000519 -0.000167  0.001348
43       -6.848 -0.000233 -0.000696 -0.000302  0.002371
43       -5.848 -0.000219 -0.000318 -0.000081  0.000541
43       -4.848 -0.000213 -0.000466 -0.000204  0.001384
...         ...       ...       ...       ...       ...
20180856 -4.848  0.003564  0.000629  0.000112 -0.000113
20180856 -3.848  0.002420  0.000482  0.000044 -0.000098
20180856 -2.848  0.002654  0.000460 -0.000016 -0.000023
20180856 -1.848  0.003559  0.000682  0.000039 -0.000117
20180856 -0.848  0.002459  0.000439 -0.000004 -0.000041

[125 rows x 5 columns]

In [8]:
DCM.to_csv('Data\PCA_DCM.csv')

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\school\AppData\Local\Temp\ipykernel_2936\3565036170.py:1: SyntaxWarning: invalid escape sequence '\P'
  DCM.to_csv('Data\PCA_DCM.csv')

## Components

In [9]:
COMPS = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
COMPS.columns = ["PC{}".format(i) for i in COMPS.columns]
COMPS.index = TFIDF_L2.columns
COMPS.index.name = 'term_str'
COMPS.T

term_str,chap_num,000,1,10,100,1018,1030,10th,11,1140,...,zoöphagy,zurich,à,æneis,æra,æt,ætat,æther,état,œdipus
PC0,7.444478e+00,-2.848337e-07,3.625639e-06,-1.064590e-07,5.378454e-07,3.626565e-07,6.275959e-07,7.130132e-08,8.414410e-08,9.034563e-07,...,7.230908e-07,-1.475715e-07,-6.095192e-07,-1.886932e-08,1.100677e-07,-1.522670e-07,-3.585570e-07,-2.204716e-07,-4.331957e-08,-1.886932e-08
PC1,7.759257e-09,-1.286090e-07,-5.492522e-07,-2.128610e-07,-4.089858e-08,-5.844185e-08,-7.300637e-08,-9.239974e-08,-2.171075e-07,-4.850566e-09,...,-1.562929e-08,-1.683161e-07,9.296274e-07,-8.018963e-08,-1.428119e-07,-1.074132e-07,-1.153928e-07,-3.157957e-07,5.222678e-07,-8.018963e-08
PC2,1.017796e-08,-2.851401e-07,-5.768977e-07,-3.724106e-07,-1.375889e-07,-1.659408e-07,-1.641263e-07,-2.342620e-07,-3.610341e-07,-5.526460e-08,...,-1.084677e-07,-3.362017e-07,-3.480095e-07,-1.975266e-07,-2.530073e-07,-2.790023e-07,-3.429254e-07,-4.540914e-07,-6.981110e-08,-1.975266e-07
PC3,-6.810120e-09,2.092313e-08,1.238012e-06,-4.937691e-07,5.929738e-08,-2.076053e-07,-4.348225e-07,-3.792707e-08,-6.720943e-07,-2.377148e-07,...,-1.896213e-07,4.164145e-07,-3.410265e-07,1.463653e-08,-1.233917e-07,-4.624953e-08,-8.963146e-08,-7.319839e-07,4.337833e-08,1.463653e-08
PC4,2.961200e-09,2.605395e-08,3.623269e-07,3.395886e-07,4.353772e-08,1.904320e-07,3.498407e-07,1.967300e-07,4.555151e-07,1.870735e-07,...,1.811464e-07,-8.466927e-08,1.110830e-06,2.697152e-08,5.574210e-08,1.031454e-07,1.730065e-07,-9.126845e-07,1.694796e-09,2.697152e-08

In [10]:
COMPS.to_csv('Data\COMPS.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_2936\2445996821.py:1: SyntaxWarning: invalid escape sequence '\C'
  COMPS.to_csv('Data\COMPS.csv')

In [17]:
LIB_aligned = LIB.loc[DCM.index]

def vis_pcs(DCM, a, b, label='author', hover_name='label'):
    return px.scatter(DCM, f"PC{a}", f"PC{b}", 
                    color=LIB_aligned[label], 
                    hover_name=LIB_aligned[hover_name],
                    marginal_x='box', height=800)

def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [12]:
LIB.columns

Index(['short_name', 'era', 'date', 'novel_type'], dtype='object')

In [13]:
!pip install nbformat

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbformat in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (311)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\school\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [14]:
import nbformat

In [15]:
!pip install --upgrade kaleido

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaleido in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (1.2.0)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from kaleido) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from kaleido) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from kaleido) (3.11.8)
Requirement already satisfied: packaging in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from kaleido) (26.0)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from kaleido) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from choreographer>=1.1.1->kaleido) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pytest-timeout>=2.4.0->kaleido) (9.0.3)
Requirement already satisfied: colorama>=0.4 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (0.4.6)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.19.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\school\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# 1st 2 components

In [ ]:

vis_pcs(DCM, 0, 1, 'novel_type', 'short_name')

In [20]:
COMPS = COMPS.drop(index=['chap_num'])

In [21]:
vis_loadings(COMPS, 0, 1)

# 2nd 2 components

In [22]:
vis_pcs(DCM, 1, 2, 'novel_type', 'short_name')

In [23]:
vis_loadings(COMPS, 1, 2)

In [ ]:
!pip install --upgrade plotly

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (6.6.0)
Collecting plotly
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from plotly) (25.0)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 4.7 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.9 MB 6.2 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.9 MB 5.5 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.9 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 10.5 MB/s  0:00:01
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 6.6.0
    Uninstalling plotly-6.6.0:
      Successfully uninstalled plotly-6.6.0
Successfully installed plotly-6.7.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\school\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip