In [5]:
!pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly) (26.0)

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

In [8]:
LIB = pd.read_csv('Data\LIB.csv').set_index('book_id').dropna()
TFIDF_L2 = pd.read_csv('Data\PCA\TFIDF_L2.csv').set_index('book_id')

<>:1: SyntaxWarning: invalid escape sequence '\L'
<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\L'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\school\AppData\Local\Temp\ipykernel_21660\182301560.py:1: SyntaxWarning: invalid escape sequence '\L'
  LIB = pd.read_csv('Data\LIB.csv').set_index('book_id').dropna()
C:\Users\school\AppData\Local\Temp\ipykernel_21660\182301560.py:2: SyntaxWarning: invalid escape sequence '\P'
  TFIDF_L2 = pd.read_csv('Data\PCA\TFIDF_L2.csv').set_index('book_id')

## PCA DCM

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD

In [10]:
!pip install plotly_express

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly_express in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.4.1)
Requirement already satisfied: pandas>=0.20.0 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly_express) (2.3.1)
Requirement already satisfied: plotly>=4.1.0 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly_express) (6.7.0)
Requirement already satisfied: statsmodels>=0.9.0 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly_express) (0.14.5)
Requirement already satisfied: scipy>=0.18 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly_express) (1.16.1)
Requirement already satisfied: patsy>=0.5 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly_express) (1.0.1)
Requirement already satisfied: numpy>=1.11 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly_express) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=0.20.0->plotly_express) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=0.20.0->plotly_express) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=0.20.0->plotly_express) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly>=4.1.0->plotly_express) (2.19.0)
Requirement already satisfied: packaging in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from plotly>=4.1.0->plotly_express) (26.0)
Requirement already satisfied: six>=1.5 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas>=0.20.0->plotly_express) (1.17.0)

In [11]:
import plotly.express as px
import plotly.io as pio
pio.renderers.default = 'notebook_connected'

In [12]:
pca_engine = PCA(n_components=5)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF_L2), index=TFIDF_L2.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

            PC0       PC1       PC2       PC3       PC4
book_id
43       -8.848 -0.000228 -0.000409 -0.000012  0.000733
43       -7.848 -0.000279 -0.000519 -0.000167  0.001348
43       -6.848 -0.000233 -0.000696 -0.000302  0.002371
43       -5.848 -0.000219 -0.000318 -0.000081  0.000541
43       -4.848 -0.000213 -0.000466 -0.000204  0.001384
...         ...       ...       ...       ...       ...
20180856 -4.848  0.003564  0.000629  0.000112 -0.000113
20180856 -3.848  0.002420  0.000482  0.000044 -0.000098
20180856 -2.848  0.002654  0.000460 -0.000016 -0.000023
20180856 -1.848  0.003559  0.000682  0.000039 -0.000117
20180856 -0.848  0.002459  0.000439 -0.000004 -0.000041

[125 rows x 5 columns]

In [13]:
DCM.to_csv('Data\PCA_DCM.csv')

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\school\AppData\Local\Temp\ipykernel_21660\3565036170.py:1: SyntaxWarning: invalid escape sequence '\P'
  DCM.to_csv('Data\PCA_DCM.csv')

## Components

In [14]:
COMPS = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
COMPS.columns = ["PC{}".format(i) for i in COMPS.columns]
COMPS.index = TFIDF_L2.columns
COMPS.index.name = 'term_str'
COMPS.T

term_str,chap_num,000,1,10,100,1018,1030,10th,11,1140,...,zoöphagy,zurich,à,æneis,æra,æt,ætat,æther,état,œdipus
PC0,7.444478e+00,-2.848337e-07,3.625639e-06,-1.064590e-07,5.378454e-07,3.626565e-07,6.275959e-07,7.130132e-08,8.414410e-08,9.034563e-07,...,7.230908e-07,-1.475715e-07,-6.095192e-07,-1.886932e-08,1.100677e-07,-1.522670e-07,-3.585570e-07,-2.204716e-07,-4.331957e-08,-1.886932e-08
PC1,7.759254e-09,-1.286085e-07,-5.492483e-07,-2.128591e-07,-4.089790e-08,-5.844219e-08,-7.300713e-08,-9.239966e-08,-2.171065e-07,-4.851618e-09,...,-1.562955e-08,-1.683168e-07,9.296260e-07,-8.018935e-08,-1.428116e-07,-1.074127e-07,-1.153924e-07,-3.157957e-07,5.222675e-07,-8.018935e-08
PC2,1.017796e-08,-2.851402e-07,-5.768940e-07,-3.724095e-07,-1.375894e-07,-1.659403e-07,-1.641251e-07,-2.342626e-07,-3.610325e-07,-5.526471e-08,...,-1.084680e-07,-3.362020e-07,-3.480109e-07,-1.975268e-07,-2.530074e-07,-2.790021e-07,-3.429249e-07,-4.540914e-07,-6.981120e-08,-1.975268e-07
PC3,-6.810112e-09,2.092083e-08,1.238093e-06,-4.937815e-07,5.930375e-08,-2.076084e-07,-4.348286e-07,-3.792600e-08,-6.721075e-07,-2.377139e-07,...,-1.896227e-07,4.164064e-07,-3.410265e-07,1.463568e-08,-1.234037e-07,-4.625285e-08,-8.963082e-08,-7.319839e-07,4.337447e-08,1.463568e-08
PC4,2.961242e-09,2.604926e-08,3.622321e-07,3.395640e-07,4.352912e-08,1.904357e-07,3.498488e-07,1.967286e-07,4.555025e-07,1.870876e-07,...,1.811515e-07,-8.465860e-08,1.110842e-06,2.696837e-08,5.574115e-08,1.031386e-07,1.730028e-07,-9.126843e-07,1.700045e-09,2.696837e-08

In [15]:
COMPS.to_csv('Data\COMPS.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_21660\2445996821.py:1: SyntaxWarning: invalid escape sequence '\C'
  COMPS.to_csv('Data\COMPS.csv')

In [16]:
LIB_aligned = LIB.loc[DCM.index]

def vis_pcs(DCM, a, b, label='author', hover_name='label'):
    return px.scatter(DCM, f"PC{a}", f"PC{b}", 
                    color=LIB_aligned[label], 
                    hover_name=LIB_aligned[hover_name],
                    marginal_x='box', height=800)

def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [17]:
LIB.columns

Index(['short_name', 'era', 'date', 'novel_type'], dtype='object')

In [18]:
!pip install nbformat

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbformat in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)
Requirement already satisfied: pywin32>=300 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (311)

In [19]:
import nbformat

In [20]:
!pip install --upgrade kaleido

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaleido in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.2.0)
Requirement already satisfied: choreographer>=1.1.1 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from kaleido) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from kaleido) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from kaleido) (3.11.8)
Requirement already satisfied: packaging in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from kaleido) (26.0)
Requirement already satisfied: pytest-timeout>=2.4.0 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from kaleido) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from choreographer>=1.1.1->kaleido) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pytest-timeout>=2.4.0->kaleido) (9.0.3)
Requirement already satisfied: colorama>=0.4 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (0.4.6)
Requirement already satisfied: iniconfig>=1.0.1 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in C:\Users\school\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.19.2)

# 1st 2 components

In [21]:

vis_pcs(DCM, 0, 1, 'novel_type', 'short_name')

In [22]:
COMPS = COMPS.drop(index=['chap_num'])

In [23]:
vis_loadings(COMPS, 0, 1)

# 2nd 2 components

In [24]:
vis_pcs(DCM, 1, 2, 'novel_type', 'short_name')

In [25]:
vis_loadings(COMPS, 1, 2)

## Loadings

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

In [27]:
COMPS = pd.read_csv('Data\PCA\COMPS.csv')

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\school\AppData\Local\Temp\ipykernel_21660\1008948756.py:1: SyntaxWarning: invalid escape sequence '\P'
  COMPS = pd.read_csv('Data\PCA\COMPS.csv')

In [28]:

LOADINGS = COMPS
LOADINGS = pd.DataFrame(pca_engine.components_.T, index=TFIDF_L2.columns, columns=["PC{}".format(i) for i in range(5)])
LOADINGS.index.name = 'term_str'
LOADINGS

                   PC0       PC1       PC2       PC3       PC4
term_str
chap_num  1.000000e+00  0.000010  0.000016 -0.000012  0.000005
000      -3.826107e-08 -0.000172 -0.000436  0.000036  0.000047
1         4.870239e-07 -0.000734 -0.000882  0.002123  0.000649
10       -1.430040e-08 -0.000284 -0.000570 -0.000847  0.000608
100       7.224756e-08 -0.000055 -0.000210  0.000102  0.000078
...                ...       ...       ...       ...       ...
æt       -2.045369e-08 -0.000143 -0.000427 -0.000079  0.000185
ætat     -4.816416e-08 -0.000154 -0.000525 -0.000154  0.000310
æther    -2.961546e-08 -0.000422 -0.000695 -0.001255 -0.001634
état     -5.819021e-09  0.000698 -0.000107  0.000074  0.000003
œdipus   -2.534673e-09 -0.000107 -0.000302  0.000025  0.000048

[21505 rows x 5 columns]

In [30]:
LOADINGS.to_csv('Data/PCA/PCA_LOADINGS.csv')