In [48]:
! pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gensim in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from gensim) (2.3.1)
Requirement already satisfied: scipy>=1.7.0 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from gensim) (1.16.1)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from smart_open>=1.8.1->gensim) (2.1.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\school\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [49]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.io as pio

from gensim.corpora import Dictionary
from gensim.models import word2vec

from sklearn.manifold import TSNE as tsne   
pio.renderers.default = 'iframe'
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

In [50]:
import gensim
gensim.__version__

'4.4.0'

In [51]:
OHCO = ['book_id', 'chap_num', 'para_num', 'sent_num', 'token_num']
bags = dict(
    SENTS = OHCO[:4],
    PARAS = OHCO[:3],
    CHAPS = OHCO[:2],
    BOOKS = OHCO[:1]
)
BAG = OHCO[:4]

In [52]:
TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv').dropna().set_index(OHCO)
TOKENS.head()

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_28612\428624466.py:1: SyntaxWarning: invalid escape sequence '\C'
  TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv').dropna().set_index(OHCO)
C:\Users\school\AppData\Local\Temp\ipykernel_28612\428624466.py:1: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv').dropna().set_index(OHCO)

                                                     pos_tuple  pos token_str  \
book_id chap_num para_num sent_num token_num
3268    1        0        0        0            ('home', 'NN')   NN      home
                                   1             ('is', 'VBZ')  VBZ        is
                                   2             ('the', 'DT')   DT       the
                                   3          ('resort', 'NN')   NN    resort
                                   4              ('Of', 'IN')   IN        Of

                                             term_str pos_group
book_id chap_num para_num sent_num token_num
3268    1        0        0        0             home        NN
                                   1               is        VB
                                   2              the        DT
                                   3           resort        NN
                                   4               of        IN

In [53]:
docs = TOKENS.groupby('chap_num').term_str.apply(list).tolist()

In [54]:
for i in range(5):
    print(f"Doc {i}:", docs[i])

Doc 0: ['home', 'is', 'the', 'resort', 'of', 'love', 'of', 'joy', 'of', 'peace', 'and', 'plenty', 'where', 'supporting', 'and', 'supported', 'polish', 'd', 'friends', 'and', 'dear', 'relations', 'mingle', 'into', 'bliss', 'thomson', 'on', 'the', 'pleasant', 'banks', 'of', 'the', 'garonne', 'in', 'the', 'province', 'of', 'gascony', 'stood', 'in', 'the', 'year', '1584', 'the', 'château', 'of', 'monsieur', 'st', 'aubert', 'from', 'its', 'windows', 'were', 'seen', 'the', 'pastoral', 'landscapes', 'of', 'guienne', 'and', 'gascony', 'stretching', 'along', 'the', 'river', 'gay', 'with', 'luxuriant', 'woods', 'and', 'vine', 'and', 'plantations', 'of', 'olives', 'to', 'the', 'south', 'the', 'view', 'was', 'bounded', 'by', 'the', 'majestic', 'pyrenees', 'whose', 'summits', 'veiled', 'in', 'clouds', 'or', 'exhibiting', 'awful', 'forms', 'seen', 'and', 'lost', 'again', 'as', 'the', 'partial', 'vapours', 'rolled', 'along', 'were', 'sometimes', 'barren', 'and', 'gleamed', 'through', 'the', 'blue', 'tinge', 'of', 'air', 'and', 'sometimes', 'frowned', 'with', 'forests', 'of', 'gloomy', 'pine', 'that', 'swept', 'downward', 'to', 'their', 'base', 'these', 'tremendous', 'precipices', 'were', 'contrasted', 'by', 'the', 'soft', 'green', 'of', 'the', 'pastures', 'and', 'woods', 'that', 'hung', 'upon', 'their', 'skirts', 'among', 'whose', 'flocks', 'and', 'herds', 'and', 'simple', 'cottages', 'the', 'eye', 'after', 'having', 'scaled', 'the', 'cliffs', 'above', 'delighted', 'to', 'repose', 'to', 'the', 'north', 'and', 'to', 'the', 'east', 'the', 'plains', 'of', 'guienne', 'and', 'languedoc', 'were', 'lost', 'in', 'the', 'mist', 'of', 'distance', 'on', 'the', 'west', 'gascony', 'was', 'bounded', 'by', 'the', 'waters', 'of', 'biscay', 'm', 'st', 'aubert', 'loved', 'to', 'wander', 'with', 'his', 'wife', 'and', 'daughter', 'on', 'the', 'margin', 'of', 'the', 'garonne', 'and', 'to', 'listen', 'to', 'the', 'music', 'that', 'floated', 'on', 'its', 'waves', 'he', 'had', 'known', 'life', 'in', 'other', 'forms', 'than', 'those', 'of', 'pastoral', 'simplicity', 'having', 'mingled', 'in', 'the', 'gay', 'and', 'in', 'the', 'busy', 'scenes', 'of', 'the', 'world', 'but', 'the', 'flattering', 'portrait', 'of', 'mankind', 'which', 'his', 'heart', 'had', 'delineated', 'in', 'early', 'youth', 'his', 'experience', 'had', 'too', 'sorrowfully', 'corrected', 'yet', 'amidst', 'the', 'changing', 'visions', 'of', 'life', 'his', 'principles', 'remained', 'unshaken', 'his', 'benevolence', 'unchilled', 'and', 'he', 'retired', 'from', 'the', 'multitude', 'more', 'in', '_pity_', 'than', 'in', 'anger', 'to', 'scenes', 'of', 'simple', 'nature', 'to', 'the', 'pure', 'delights', 'of', 'literature', 'and', 'to', 'the', 'exercise', 'of', 'domestic', 'virtues', 'he', 'was', 'a', 'descendant', 'from', 'the', 'younger', 'branch', 'of', 'an', 'illustrious', 'family', 'and', 'it', 'was', 'designed', 'that', 'the', 'deficiency', 'of', 'his', 'patrimonial', 'wealth', 'should', 'be', 'supplied', 'either', 'by', 'a', 'splendid', 'alliance', 'in', 'marriage', 'or', 'by', 'success', 'in', 'the', 'intrigues', 'of', 'public', 'affairs', 'but', 'st', 'aubert', 'had', 'too', 'nice', 'a', 'sense', 'of', 'honour', 'to', 'fulfil', 'the', 'latter', 'hope', 'and', 'too', 'small', 'a', 'portion', 'of', 'ambition', 'to', 'sacrifice', 'what', 'he', 'called', 'happiness', 'to', 'the', 'attainment', 'of', 'wealth', 'after', 'the', 'death', 'of', 'his', 'father', 'he', 'married', 'a', 'very', 'amiable', 'woman', 'his', 'equal', 'in', 'birth', 'and', 'not', 'his', 'superior', 'in', 'fortune', 'the', 'late', 'monsieur', 'st', 'aubert', 's', 'liberality', 'or', 'extravagance', 'had', 'so', 'much', 'involved', 'his', 'affairs', 'that', 'his', 'son', 'found', 'it', 'necessary', 'to', 'dispose', 'of', 'a', 'part', 'of', 'the', 'family', 'domain', 'and', 'some', 'years', 'after', 'his', 'marriage', 'he', 'sold', 'it', 'to', 'monsieur', 'quesnel', 'the', 'brother', 'of', 'his', 'wife', 'and', 'retired', 'to', 'a', 'small', 'estate', 'in', 'gascony', 'where', 'conjugal', 'felicity', 'and', 'parental', 'duties', 'divided', 'his', 'attention', 'with', 'the', 'treasures', 'of', 'knowledge', 'and', 'the', 'illuminations', 'of', 'genius', 'to', 'this', 'spot', 'he', 'had', 'been', 'attached', 'from', 'his', 'infancy', 'he', 'had', 'often', 'made', 'excursions', 'to', 'it', 'when', 'a', 'boy', 'and', 'the', 'impressions', 'of', 'delight', 'given', 'to', 'his', 'mind', 'by', 'the', 'homely', 'kindness', 'of', 'the', 'greyheaded', 'peasant', 'to', 'whom', 'it', 'was', 'intrusted', 'and', 'whose', 'fruit', 'and', 'cream', 'never', 'failed', 'had', 'not', 'been', 'obliterated', 'by', 'succeeding', 'circumstances', 'the', 'green', 'pastures', 'along', 'which', 'he', 'had', 'so', 'often', 'bounded', 'in', 'the', 'exultation', 'of', 'health', 'and', 'youthful', 'freedomthe', 'woods', 'under', 'whose', 'refreshing', 'shade', 'he', 'had', 'first', 'indulged', 'that', 'pensive', 'melancholy', 'which', 'afterwards', 'made', 'a', 'strong', 'feature', 'of', 'his', 'characterthe', 'wild', 'walks', 'of', 'the', 'mountains', 'the', 'river', 'on', 'whose', 'waves', 'he', 'had', 'floated', 'and', 'the', 'distant', 'plains', 'which', 'seemed', 'boundless', 'as', 'his', 'early', 'hopeswere', 'never', 'after', 'remembered', 'by', 'st', 'aubert', 'but', 'with', 'enthusiasm', 'and', 'regret', 'at', 'length', 'he', 'disengaged', 'himself', 'from', 'the', 'world', 'and', 'retired', 'hither', 'to', 'realise', 'the', 'wishes', 'of', 'many', 'years', 'the', 'building', 'as', 'it', 'then', 'stood', 'was', 'merely', 'a', 'summer', 'cottage', 'rendered', 'interesting', 'to', 'a', 'stranger', 'by', 'its', 'neat', 'simplicity', 'or', 'the', 'beauty', 'of', 'the', 'surrounding', 'scene', 'and', 'considerable', 'additions', 'were', 'necessary', 'to', 'make', 'it', 'a', 'comfortable', 'family', 'residence', 'st', 'aubert', 'felt', 'a', 'kind', 'of', 'affection', 'for', 'every', 'part', 'of', 'the', 'fabric', 'which', 'he', 'remembered', 'in', 'his', 'youth', 'and', 'would', 'not', 'suffer', 'a', 'stone', 'of', 'it', 'to', 'be', 'removed', 'so', 'that', 'the', 'new', 'building', 'adapted', 'to', 'the', 'style', 'of', 'the', 'old', 'one', 'formed', 'with', 'it', 'only', 'a', 'simple', 'and', 'elegant', 'residence', 'the', 'taste', 'of', 'madame', 'st', 'aubert', 'was', 'conspicuous', 'in', 'its', 'internal', 'finishing', 'where', 'the', 'same', 'chaste', 'simplicity', 'was', 'observable', 'in', 'the', 'furniture', 'and', 'in', 'the', 'few', 'ornaments', 'of', 'the', 'apartments', 'that', 'characterised', 'the', 'manners', 'of', 'its', 'inhabitants', 'the', 'library', 'occupied', 'the', 'west', 'side', 'of', 'the', 'château', 'and', 'was', 'enriched', 'by', 'a', 'collection', 'of', 'the', 'best', 'books', 'in', 'the', 'ancient', 'and', 'modern', 'languages', 'this', 'room', 'opened', 'upon', 'a', 'grove', 'which', 'stood', 'on', 'the', 'brow', 'of', 'a', 'gentle', 'declivity', 'that', 'fell', 'towards', 'the', 'river', 'and', 'the', 'tall', 'trees', 'gave', 'it', 'a', 'melancholy', 'and', 'pleasing', 'shade', 'while', 'from', 'the', 'windows', 'the', 'eye', 'caught', 'beneath', 'the', 'spreading', 'branches', 'the', 'gay', 'and', 'luxuriant', 'landscape', 'stretching', 'to', 'the', 'west', 'and', 'overlooked', 'on', 'the', 'left', 'by', 'the', 'bold', 'precipices', 'of', 'the', 'pyrenees', 'adjoining', 'the', 'library', 'was', 'a', 'greenhouse', 'stored', 'with', 'scarce', 'and', 'beautiful', 'plants', 'for', 'one', 'of', 'the', 'amusements', 'of', 'st', 'aubert', 'was', 'the', 'study', 'of', 'botany', 'and', 'among', 'the', 'neighbouring', 'mountains', 'which', 'afforded', 'a', 'luxurious', 'feast', 'to', 'the', 'mind', 'of', 'the', 'naturalist', 'he', 'often', 'passed', 'the', 'day', 'in', 'the', 'pursuit', 'of', 'his', 'favourite', 'science', 'he', 'was', 'sometimes', 'accompanied', 'in', 'these', 'little', 'excursions', 'by', 'madame', 'st', 'aubert', 'and', 'frequently', 'by', 'his', 'daughter', 'when', 'with', 'a', 'small', 'osier', 'basket', 'to', 'receive', 'plants', 'and', 'another', 'filled', 'with', 'cold', 'refreshments', 'such', 'as', 'the', 'cabin', 'of', 'the', 'shepherd', 'did', 'not', 'afford', 'they', 'wandered', 'away', 'among', 'the', 'most', 'romantic', 'and', 'magnificent', 'scenes', 'nor', 'suffered', 'the', 'charms', 'of', 'nature', 's', 'lowly', 'children', 'to', 'abstract', 'them', 'from', 'the', 'observance', 'of', 'her', 'stupendous', 'works', 'when', 'weary', 'of', 'sauntering', 'among', 'cliffs', 'that', 'seemed', 'scarcely', 'accessible', 'but', 'to', 'the', 'steps', 'of', 'the', 'enthusiast', 'and', 'where', 'no', 'track', 'appeared', 'on', 'the', 'vegetation', 'but', 'what', 'the', 'foot', 'of', 'the', 'izard', 'had', 'left', 'they', 'would', 'seek', 'one', 'of', 'those', 'green', 'recesses', 'which', 'so', 'beautifully', 'adorn', 'the', 'bosom', 'of', 'these', 'mountains', 'where', 'under', 'the', 'shade', 'of', 'the', 'lofty', 'larch', 'or', 'cedar', 'they', 'enjoyed', 'their', 'simple', 'repast', 'made', 'sweeter', 'by', 'the', 'waters', 'of', 'the', 'cool', 'stream', 'that', 'crept', 'along', 'the', 'turf', 'and', 'by', 'the', 'breath', 'of', 'wild', 'flowers', 'and', 'aromatic', 'plants', 'that', 'fringed', 'the', 'rocks', 'and', 'inlaid', 'the', 'grass', 'adjoining', 'the', 'eastern', 'side', 'of', 'the', 'greenhouse', 'looking', 'towards', 'the', 'plains', 'of', 'languedoc', 'was', 'a', 'room', 'which', 'emily', 'called', 'hers', 'and', 'which', 'contained', 'her', 'books', 'her', 'drawings', 'her', 'musical', 'instruments', 'with', 'some', 'favourite', 'birds', 'and', 'plants', 'here', 'she', 'usually', 'exercised', 'herself', 'in', 'elegant', 'arts', 'cultivated', 'only', 'because', 'they', 'were', 'congenial', 'to', 'her', 'taste', 'and', 'in', 'which', 'native', 'genius', 'assisted', 'by', 'the', 'instructions', 'of', 'monsieur', 'and', 'madame', 'st', 'aubert', 'made', 'her', 'an', 'early', 'proficient', 'the', 'windows', 'of', 'this', 'room', 'were', 'particularly', 'pleasant', 'they', 'descended', 'to', 'the', 'floor', 'and', 'opening', 'upon', 'the', 'little', 'lawn', 'that', 'surrounded', 'the', 'house', 'the', 'eye', 'was', 'led', 'between', 'groves', 'of', 'almond', 'palmtrees', 'floweringash', 'and', 'myrtle', 'to', 'the', 'distant', 'landscape', 'where', 'the', 'garonne', 'wandered', 'the', 'peasants', 'of', 'this', 'gay', 'climate', 'were', 'often', 'seen', 'on', 'an', 'evening', 'when', 'the', 'day', 's', 'labour', 'was', 'done', 'dancing', 'in', 'groups', 'on', 'the', 'margin', 'of', 'the', 'river', 'their', 'sprightly', 'melodies', '_debonnaire_', 'steps', 'the', 'fanciful', 'figure', 'of', 'their', 'dances', 'with', 'the', 'tasteful', 'and', 'capricious', 'manner', 'in', 'which', 'the', 'girls', 'adjusted', 'their', 'simple', 'dress', 'gave', 'a', 'character', 'to', 'the', 'scene', 'entirely', 'french', 'the', 'front', 'of', 'the', 'château', 'which', 'having', 'a', 'southern', 'aspect', 'opened', 'upon', 'the', 'grandeur', 'of', 'the', 'mountains', 'was', 'occupied', 'on', 'the', 'ground', 'floor', 'by', 'a', 'rustic', 'hall', 'and', 'two', 'excellent', 'sitting', 'rooms', 'the', 'first', 'floor', 'for', 'the', 'cottage', 'had', 'no', 'second', 'story', 'was', 'laid', 'out', 'in', 'bedchambers', 'except', 'one', 'apartment', 'that', 'opened', 'to', 'a', 'balcony', 'and', 'which', 'was', 'generally', 'used', 'for', 'a', 'breakfastroom', 'in', 'the', 'surrounding', 'ground', 'st', 'aubert', 'had', 'made', 'very', 'tasteful', 'improvements', 'yet', 'such', 'was', 'his', 'attachment', 'to', 'objects', 'he', 'had', 'remembered', 'from', 'his', 'boyish', 'days', 'that', 'he', 'had', 'in', 'some', 'instances', 'sacrificed', 'taste', 'to', 'sentiment', 'there', 'were', 'two', 'old', 'larches', 'that', 'shaded', 'the', 'building', 'and', 'interrupted', 'the', 'prospect', 'st', 'aubert', 'had', 'sometimes', 'declared', 'that', 'he', 'believed', 'he', 'should', 'have', 'been', 'weak', 'enough', 'to', 'have', 'wept', 'at', 'their', 'fall', 'in', 'addition', 'to', 'these', 'larches', 'he', 'planted', 'a', 'little', 'grove', 'of', 'beech', 'pine', 'and', 'mountainash', 'on', 'a', 'lofty', 'terrace', 'formed', 'by', 'the', 'swelling', 'bank', 'of', 'the', 'river', 'rose', 'a', 'plantation', 'of', 'orange', 'lemon', 'and', 'palmtrees', 'whose', 'fruit', 'in', 'the', 'coolness', 'of', 'evening', 'breathed', 'delicious', 'fragrance', 'with', 'these', 'were', 'mingled', 'a', 'few', 'trees', 'of', 'other', 'species', 'here', 'under', 'the', 'ample', 'shade', 'of', 'a', 'planetree', 'that', 'spread', 'its', 'majestic', 'canopy', 'towards', 'the', 'river', 'st', 'aubert', 'loved', 'to', 'sit', 'in', 'the', 'fine', 'evenings', 'of', 'summer', 'with', 'his', 'wife', 'and', 'children', 'watching', 'beneath', 'its', 'foliage', 'the', 'setting', 'sun', 'the', 'mild', 'splendour', 'of', 'its', 'light', 'fading', 'from', 'the', 'distant', 'landscape', 'till', 'the', 'shadows', 'of', 'twilight', 'melted', 'its', 'various', 'features', 'into', 'one', 'tint', 'of', 'sober', 'grey', 'here', 'too', 'he', 'loved', 'to', 'read', 'and', 'to', 'converse', 'with', 'madame', 'st', 'aubert', 'or', 'to', 'play', 'with', 'his', 'children', 'resigning', 'himself', 'to', 'the', 'influence', 'of', 'those', 'sweet', 'affections', 'which', 'are', 'ever', 'attendant', 'on', 'simplicity', 'and', 'nature', 'he', 'has', 'often', 'said', 'while', 'tears', 'of', 'pleasure', 'trembled', 'in', 'his', 'eyes', 'that', 'these', 'were', 'moments', 'infinitely', 'more', 'delightful', 'than', 'any', 'passed', 'amid', 'the', 'brilliant', 'and', 'tumultuous', 'scenes', 'that', 'are', 'courted', 'by', 'the', 'world', 'his', 'heart', 'was', 'occupied', 'it', 'had', 'what', 'can', 'be', 'so', 'rarely', 'said', 'no', 'wish', 'for', 'a', 'happiness', 'beyond', 'what', 'it', 'experienced', 'the', 'consciousness', 'of', 'acting', 'right', 'diffused', 'a', 'serenity', 'over', 'his', 'manners', 'which', 'nothing', 'else', 'could', 'impart', 'to', 'a', 'man', 'of', 'moral', 'perceptions', 'like', 'his', 'and', 'which', 'refined', 'his', 'sense', 'of', 'every', 'surrounding', 'blessing', 'the', 'deepest', 'shade', 'of', 'twilight', 'did', 'not', 'send', 'him', 'from', 'his', 'favourite', 'planetree', 'he', 'loved', 'the', 'soothing', 'hour', 'when', 'the', 'last', 'tints', 'of', 'light', 'die', 'away', 'when', 'the', 'stars', 'one', 'by', 'one', 'tremble', 'through', 'æther', 'and', 'are', 'reflected', 'on', 'the', 'dark', 'mirror', 'of', 'the', 'waters', 'that', 'hour', 'which', 'of', 'all', 'others', 'inspires', 'the', 'mind', 'with', 'pensive', 'tenderness', 'and', 'often', 'elevates', 'it', 'to', 'sublime', 'contemplation', 'when', 'the', 'moon', 'shed', 'her', 'soft', 'rays', 'among', 'the', 'foliage', 'he', 'still', 'lingered', 'and', 'his', 'pastoral', 'supper', 'of', 'cream', 'and', 'fruits', 'was', 'often', 'spread', 'beneath', 'it', 'then', 'on', 'the', 'stillness', 'of', 'night', 'came', 'the', 'song', 'of', 'the', 'nightingale', 'breathing', 'sweetness', 'and', 'awakening', 'melancholy', 'the', 'first', 'interruptions', 'to', 'the', 'happiness', 'he', 'had', 'known', 'since', 'his', 'retirement', 'were', 'occasioned', 'by', 'the', 'death', 'of', 'his', 'two', 'sons', 'he', 'lost', 'them', 'at', 'that', 'age', 'when', 'infantine', 'simplicity', 'is', 'so', 'fascinating', 'and', 'though', 'in', 'consideration', 'of', 'madame', 'st', 'aubert', 's', 'distress', 'he', 'restrained', 'the', 'expression', 'of', 'his', 'own', 'and', 'endeavoured', 'to', 'bear', 'it', 'as', 'he', 'meant', 'with', 'philosophy', 'he', 'had', 'in', 'truth', 'no', 'philosophy', 'that', 'could', 'render', 'him', 'calm', 'to', 'such', 'losses', 'one', 'daughter', 'was', 'now', 'his', 'only', 'surviving', 'child', 'and', 'while', 'he', 'watched', 'the', 'unfolding', 'of', 'her', 'infant', 'character', 'with', 'anxious', 'fondness', 'he', 'endeavoured', 'with', 'unremitting', 'effort', 'to', 'counteract', 'those', 'traits', 'in', 'her', 'disposition', 'which', 'might', 'hereafter', 'lead', 'her', 'from', 'happiness', 'she', 'had', 'discovered', 'in', 'her', 'early', 'years', 'uncommon', 'delicacy', 'of', 'mind', 'warm', 'affections', 'and', 'ready', 'benevolence', 'but', 'with', 'these', 'was', 'observable', 'a', 'degree', 'of', 'susceptibility', 'too', 'exquisite', 'to', 'admit', 'of', 'lasting', 'peace', 'as', 'she', 'advanced', 'in', 'youth', 'this', 'sensibility', 'gave', 'a', 'pensive', 'tone', 'to', 'her', 'spirits', 'and', 'a', 'softness', 'to', 'her', 'manner', 'which', 'added', 'grace', 'to', 'beauty', 'and', 'rendered', 'her', 'a', 'very', 'interesting', 'object', 'to', 'persons', 'of', 'a', 'congenial', 'disposition', 'but', 'st', 'aubert', 'had', 'too', 'much', 'good', 'sense', 'to', 'prefer', 'a', 'charm', 'to', 'a', 'virtue', 'and', 'had', 'penetration', 'enough', 'to', 'see', 'that', 'this', 'charm', 'was', 'too', 'dangerous', 'to', 'its', 'possessor', 'to', 'be', 'allowed', 'the', 'character', 'of', 'a', 'blessing', 'he', 'endeavoured', 'therefore', 'to', 'strengthen', 'her', 'mind', 'to', 'enure', 'her', 'to', 'habits', 'of', 'selfcommand', 'to', 'teach', 'her', 'to', 'reject', 'the', 'first', 'impulse', 'of', 'her', 'feelings', 'and', 'to', 'look', 'with', 'cool', 'examination', 'upon', 'the', 'disappointments', 'he', 'sometimes', 'threw', 'in', 'her', 'way', 'while', 'he', 'instructed', 'her', 'to', 'resist', 'first', 'impressions', 'and', 'to', 'acquire', 'that', 'steady', 'dignity', 'of', 'mind', 'that', 'can', 'alone', 'counterbalance', 'the', 'passions', 'and', 'bear', 'us', 'as', 'far', 'as', 'is', 'compatible', 'with', 'our', 'nature', 'above', 'the', 'reach', 'of', 'circumstances', 'he', 'taught', 'himself', 'a', 'lesson', 'of', 'fortitude', 'for', 'he', 'was', 'often', 'obliged', 'to', 'witness', 'with', 'seeming', 'indifference', 'the', 'tears', 'and', 'struggles', 'which', 'his', 'caution', 'occasioned', 'her', 'in', 'person', 'emily', 'resembled', 'her', 'mother', 'having', 'the', 'same', 'elegant', 'symmetry', 'of', 'form', 'the', 'same', 'delicacy', 'of', 'features', 'and', 'the', 'same', 'blue', 'eyes', 'full', 'of', 'tender', 'sweetness', 'but', 'lovely', 'as', 'was', 'her', 'person', 'it', 'was', 'the', 'varied', 'expression', 'of', 'her', 'countenance', 'as', 'conversation', 'awakened', 'the', 'nicer', 'emotions', 'of', 'her', 'mind', 'that', 'threw', 'such', 'a', 'captivating', 'grace', 'around', 'her', 'those', 'tend', 'rer', 'tints', 'that', 'shun', 'the', 'careless', 'eye', 'and', 'in', 'the', 'world', 's', 'contagious', 'circle', 'die', 'st', 'aubert', 'cultivated', 'her', 'understanding', 'with', 'the', 'most', 'scrupulous', 'care', 'he', 'gave', 'her', 'a', 'general', 'view', 'of', 'the', 'sciences', 'and', 'an', 'exact', 'acquaintance', 'with', 'every', 'part', 'of', 'elegant', 'literature', 'he', 'taught', 'her', 'latin', 'and', 'english', 'chiefly', 'that', 'she', 'might', 'understand', 'the', 'sublimity', 'of', 'their', 'best', 'poets', 'she', 'discovered', 'in', 'her', 'early', 'years', 'a', 'taste', 'for', 'works', 'of', 'genius', 'and', 'it', 'was', 'st', 'aubert', 's', 'principle', 'as', 'well', 'as', 'his', 'inclination', 'to', 'promote', 'every', 'innocent', 'means', 'of', 'happiness', 'a', 'wellinformed', 'mind', 'he', 'would', 'say', 'is', 'the', 'best', 'security', 'against', 'the', 'contagion', 'of', 'folly', 'and', 'of', 'vice', 'the', 'vacant', 'mind', 'is', 'ever', 'on', 'the', 'watch', 'for', 'relief', 'and', 'ready', 'to', 'plunge', 'into', 'error', 'to', 'escape', 'from', 'the', 'languor', 'of', 'idleness', 'store', 'it', 'with', 'ideas', 'teach', 'it', 'the', 'pleasure', 'of', 'thinking', 'and', 'the', 'temptations', 'of', 'the', 'world', 'without', 'will', 'be', 'counteracted', 'by', 'the', 'gratifications', 'derived', 'from', 'the', 'world', 'within', 'thought', 'and', 'cultivation', 'are', 'necessary', 'equally', 'to', 'the

In [55]:
dictionary = Dictionary(docs)

In [56]:
w2v_params = dict(
    window = 2,
    vector_size = 200,
    min_count = 20, 
    workers = 4
)

In [57]:
model = word2vec.Word2Vec(docs, **w2v_params)
model.wv.vectors

array([[ 0.05903487, -0.06442545,  0.01589599, ..., -0.18408342,
        -0.08106686,  0.16957852],
       [ 0.02133633, -0.04350285, -0.02205697, ..., -0.26438844,
         0.0294272 , -0.01395348],
       [-0.01549195, -0.08081064,  0.01707458, ..., -0.27186596,
         0.05243788,  0.07718795],
       ...,
       [-0.00145294, -0.00947462, -0.00442233, ..., -0.03797146,
         0.00297395,  0.00890062],
       [-0.00788506, -0.01491002, -0.00987559, ..., -0.07624837,
        -0.00587841,  0.0175112 ],
       [-0.01146993, -0.02449192, -0.008845  , ..., -0.12107828,
        -0.00241766,  0.02061617]], shape=(1159, 200), dtype=float32)

In [58]:
WV = pd.DataFrame(model.wv.vectors, index=model.wv.index_to_key)
WV.index.name = 'term_str'
WV

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
term_str,,,,,,,,,,,,,,,,,,,,,
the,0.059035,-0.064425,0.015896,-0.034286,-0.282847,-0.158934,0.049125,0.445721,0.069948,0.025071,...,0.160918,0.048726,-0.284503,-0.331050,0.004532,-0.076600,0.141305,-0.184083,-0.081067,0.169579
to,0.021336,-0.043503,-0.022057,0.159433,0.052832,-0.087951,0.113449,0.262198,-0.125060,0.074498,...,0.124700,0.015008,-0.222204,-0.191695,0.075538,0.017158,0.163010,-0.264388,0.029427,-0.013953
and,-0.015492,-0.080811,0.017075,0.104479,-0.119140,-0.130778,0.121189,0.308574,-0.033145,0.066874,...,0.205301,0.043717,-0.261187,-0.273162,-0.011833,-0.064964,0.164570,-0.271866,0.052438,0.077188
of,0.026750,-0.165190,0.068235,0.107802,-0.151508,-0.117173,0.104743,0.305290,-0.001775,0.052107,...,0.306276,-0.055802,-0.335685,-0.314282,-0.070196,-0.092599,0.134072,-0.337424,0.131916,0.055238
i,0.055436,0.069592,-0.139178,0.292266,0.239550,-0.124195,0.275336,0.375828,-0.346557,0.017782,...,-0.004374,0.124252,-0.177592,-0.027519,0.208094,0.130996,0.109963,-0.147230,-0.110208,-0.094194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
books,-0.009014,-0.015744,-0.009786,0.045553,-0.026801,-0.044324,0.056010,0.119446,-0.032506,0.022296,...,0.052283,0.030172,-0.091872,-0.087974,0.014399,-0.014824,0.075667,-0.091148,-0.001936,0.020749
formed,-0.005778,-0.025844,-0.012585,0.068867,-0.029474,-0.061012,0.069215,0.148939,-0.044078,0.036977,...,0.062242,0.042052,-0.119167,-0.108631,0.018974,-0.019634,0.085637,-0.116717,-0.000469,0.017470
duties,-0.001453,-0.009475,-0.004422,0.024734,-0.014118,-0.023642,0.022646,0.055171,-0.012003,0.007727,...,0.025225,0.009066,-0.037711,-0.037489,0.003156,-0.001222,0.034729,-0.037971,0.002974,0.008901
success,-0.007885,-0.014910,-0.009876,0.042137,-0.016019,-0.038147,0.045661,0.101577,-0.027945,0.023059,...,0.037459,0.033209,-0.071882,-0.071667,0.014912,-0.006805,0.065661,-0.076248,-0.005878,0.017511
languedoc,-0.011470,-0.024492,-0.008845,0.055370,-0.037343,-0.067889,0.072233,0.160033,-0.033010,0.032790,...,0.066694,0.048945,-0.116392,-0.112930,0.021090,-0.014972,0.099719,-0.121078,-0.002418,0.020616

In [59]:
WV.to_csv('Data/w2v.csv')

# tSNE plot

In [60]:
PP = 40 #40 # Try 1, 100, etc.

tsne_engine = tsne(
    perplexity=PP, 
    n_components=2, 
    init='pca', 
    max_iter=2500, 
    random_state=23
)
TSNE = pd.DataFrame(
    tsne_engine.fit_transform(WV), 
    columns=['x','y'], 
    index=WV.index)
TSNE

                   x          y
term_str
the       -59.813187  -4.995743
to        -40.611248  12.525746
and       -56.756390  -6.547927
of        -56.623508  -7.754403
i         -29.956432  23.767076
...              ...        ...
books      54.956055   2.423887
formed     31.607893  -7.775099
duties     74.435898  15.054900
success    64.563705  10.125777
languedoc  29.270086 -11.232036

[1159 rows x 2 columns]

In [61]:
px.scatter(TSNE.reset_index(), 'x', 'y', 
        text='term_str', 
        hover_name='term_str',  
        # size='n',
        height=1000,
        width=1200)\
    .update_traces(
        mode='markers+text', 
        textfont=dict(color='black', size=14, family='Arial'),
        textposition='top center')\
    .write_image('Outputs/w2v_scatter.png')